---
label: Settings
hide_body: true
fields:
- type: text
  name: baseURL
  label: baseURL
- type: text
  name: languageCode
  label: languageCode
- type: text
  name: title
  label: title
- type: text
  name: theme
  label: theme
- type: field_group
  name: params
  label: params
  fields:
  - type: text
    name: author
    label: author
  - type: text
    name: description
    label: description
  - type: file
    name: avatar
    label: avatar
  - type: field_group_list
    name: social
    label: social
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: url
      label: url
pages:
- config.toml
